#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(dygraphs)
library(quantmod)


# Define UI for application that draws a histogram
shinyUI(fluidPage(
  
  # Application title
  column(12,align="center",titlePanel("Stock Watch")),
  
  fluidRow(
    column(12,align="center",
           tags$p("Insert stocks symbols in CAPS separated by spaces"),
           textInput("symbols","",value = "AAPL GOOG"),
           tags$p("Interact with the chart by hovering over the lines")
    )
  ),
  fluidRow(
    dygraphOutput("time_series")
  ),
  fluidRow(
    column(12, align="center",
           tags$br(),
           tags$p("(1) The numbers in the chart are generated by the percentage increase in the closing price of stocks from the price in the first day of this year."),
           tags$p("(2) There is an averaging of n values of the stock percentage to avoid overplotting it is controlled by the number on the bottom-left corner of the graph (set to 10 by default)."),
           tags$p("(3) The slider in the bottom of the graph serves to adjust the amount of time observations desired."),
           tags$p("(4) The chart was created with the package dygraph and the data was obtained from yahoo using the quantmod package."),
           tags$h3("By Flemming")
    )
  )
  
  
)
)
